import { LenisProvider } from "@/components/LenisProvider";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Prata } from "next/font/google";
import "./globals.css";

const inter = Prata({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Mystic Paradise Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LenisProvider isRoot>
        <body
          className={`${inter.className}  antialiased w-full flex justify-center gradient1 overflow-hidden`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
      </LenisProvider>
    </html>
  );
}
