const basePathImageRooms = "/rooms";
export const ROOMS = [
  { url: `${basePathImageRooms}/1.webp`, id: 1 },
  { url: `${basePathImageRooms}/3.webp`, id: 3 },
  { url: `${basePathImageRooms}/8.webp`, id: 8 },
  { url: `${basePathImageRooms}/4.webp`, id: 4 },
  { url: `${basePathImageRooms}/5.webp`, id: 5 },
  { url: `${basePathImageRooms}/6.webp`, id: 6 },
  { url: `${basePathImageRooms}/7.webp`, id: 7 },
  { url: `${basePathImageRooms}/9.webp`, id: 9 },
  { url: `${basePathImageRooms}/10.webp`, id: 10 },
  { url: `${basePathImageRooms}/11.webp`, id: 11 },
  // { url: `${basePathImageRooms}/12.webp`, id: 12 },
  { url: `${basePathImageRooms}/13.webp`, id: 13 },
  { url: `${basePathImageRooms}/14.webp`, id: 14 },
  { url: `${basePathImageRooms}/2.webp`, id: 2 },
  { url: `${basePathImageRooms}/15.webp`, id: 15 },
  { url: `${basePathImageRooms}/17.webp`, id: 17 },
  { url: `${basePathImageRooms}/16.webp`, id: 16 },
];
